# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless defined? OUTPUT_VERBOSITY
  # Output Verbosity 0..3 least..most
  if ENV['OUTPUT_VERBOSITY'].nil?
    OUTPUT_VERBOSITY = '3'
  else
    OUTPUT_VERBOSITY = ENV['OUTPUT_VERBOSITY']
  end
end

unless defined? STATIC_IP_DATAVERSE 
  STATIC_IP_DATAVERSE = "192.168.50.20"
end

unless defined? STATIC_IP_CDH 
  STATIC_IP_CDH = "192.168.50.10"
end

unless defined? ZOOKEEPER_ENSEMBLE
  ZOOKEEPER_ENSEMBLE = "quickstart.cloudera:2181"
end

unless defined? ENABLE_TLS_ON_SOLR
  # Set this to non-zero to configure the solr service to use TLS/SSL
  if ENV['ENABLE_TLS_ON_SOLR'].nil?
    ENABLE_TLS_ON_SOLR = 0
  else
    ENABLE_TLS_ON_SOLR = ENV['ENABLE_TLS_ON_SOLR']
  end
end

unless defined? TRUSTSTORE_PATH
  TRUSTSTORE_PATH = '/etc/pki/java/dataverse_truststore.jks'
end

unless defined? TRUSTSTORE_PASSWORD
  TRUSTSTORE_PASSWORD = 'dataverse'
end

unless defined? DVCOLLECTION_NAME
  DVCOLLECTION_NAME = 'dvcollection'
end

unless defined? DATAVERSE_HOME
  DATAVERSE_HOME = "/home/glassfish/glassfish4/glassfish/domains/domain1"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.synced_folder "../../../", "/dataverse"
  config.vm.provision "killFirewall", type: "shell", inline: "service iptables stop"

  config.vm.define "cdh" do |cdh|
    cdh.vm.hostname = "quickstart.cloudera"
    cdh.vm.box = "UNCC-DSI/cloudera-quickstart"
    cdh.vm.box_version = "~> 5.4.0"
    cdh.vm.network "private_network", ip: STATIC_IP_CDH
    cdh.vm.graceful_halt_timeout = 180

    cdh.vm.provision "createDataverseCollection", type: "shell", 
          path: "../setup-dvcollection.sh", 
          args: "-c '#{DVCOLLECTION_NAME}' -v #{OUTPUT_VERBOSITY} -r 1 -s 1"
      
  end

  config.vm.define "dataverse", primary: true do |dataverse|
    dataverse.vm.hostname = "dataverse"
    dataverse.vm.box = "puppetlabs/centos-6.6-64-puppet"
    dataverse.vm.network "private_network", ip: STATIC_IP_DATAVERSE
    
    unless defined? mailserver
      mailserver = "localhost"
      if ENV['MAIL_SERVER'].nil?
        puts "MAIL_SERVER environment variable not specified. Using #{mailserver} by default.\nTo specify it in bash: export MAIL_SERVER=localhost"
      else
        mailserver = ENV['MAIL_SERVER']
        puts "MAIL_SERVER environment variable found, using #{mailserver}"
      end
    end

    dataverse.vm.provision "dataversePrereqs", type: "shell", 
      path: "../setup.sh", args: "-v #{OUTPUT_VERBOSITY}"

#    if (ENABLE_TLS_ON_SOLR != 0)
#      dataverse.vm.provision "addGlassfishDomainTLS", type: "shell", 
#        path: "../setup-tls-dataverse.sh",
#        args: "-v #{OUTPUT_VERBOSITY} -w #{TRUSTSTORE_PASSWORD} -x #{STATIC_IP_DATAVERSE}" 
#      dataverse.vm.provision "addTrustToGlassfishDomain", type: "shell", 
#        inline: "keytool -importkeystore -noprompt -srckeystore /vagrant/dataverse_truststore.jks -srcstorepass #{KEYSTORE_PASSWORD} -destkeystore #{DATAVERSE_HOME}/config/cacerts.jks -deststorepass changeit"
#
#      STATIC_IP_SOLRCLOUD.each_with_index { |node,index|
#        dataverse.vm.provision "remoteAddTrustRestartSolrCloud" + (index + 1).to_s, type: "shell", 
#          inline: "ssh -o StrictHostKeyChecking=no -i /vagrant/.vagrant/machines/solrcloud" + (index + 1).to_s + "/virtualbox/private_key vagrant@#{node} 'sudo cp /vagrant/dataverse_truststore.jks #{TRUSTSTORE_PATH}; sudo service solr restart'"      
#      }
#
#      dataverse.vm.provision "cleanupTmpTrustore", type: "shell", inline: "rm /vagrant/dataverse_truststore.jks"
#    end

    dataverse.vm.provision "addHosts", type: "shell", inline: "echo \"#{STATIC_IP_CDH}     quickstart.cloudera     quickstart\" >> /etc/hosts"

    dataverse.vm.provision "dataverseSetup", type: "shell", path: "../install-dataverse.sh",
      args: "-c #{DVCOLLECTION_NAME} -h #{STATIC_IP_DATAVERSE} -m #{mailserver} -z '#{ZOOKEEPER_ENSEMBLE}' -u #{ENABLE_TLS_ON_SOLR} -v #{OUTPUT_VERBOSITY}"

    dataverse.vm.provision "dvTestUsers", type: "shell", path: "../setup-dv-test_addUsers.sh"
    dataverse.vm.provision "dvTestPublishRoot", type: "shell", path: "../setup-dv-test_publishRoot.sh"
    dataverse.vm.provision "dvTestSetupUserDVs", type: "shell", path: "../setup-dv-test_setupUserDVs.sh"
  end

end
